### ISSUE TITLE
[Bug] setting SideMenuView.MenuGestureEnabled to False blocks changes on SideMenu.State

### ISSUE THREAD

**Issue by gsgou** [AndreiMisiukevich/SideMenu#1]

**Comment by AndreiMisiukevich** [comment]
Hi, this property exists https://github.com/AndreiMisiukevich/SideMenu/blob/master/SideMenu/SideMenuView.cs#L53
This is an attached one.

But I suggest you to switch to https://github.com/xamarin/XamarinCommunityToolkit

SideMenu is merged there

**Comment by gsgou** [comment]
@AndreiMisiukevich setting MenuGestureEnabledProperty to False does not only disable the pan gesture but does not allow over a Command to change SideMenu.State in the sample. Is this a bug or do i misunderstand the purpose of the property?
Tks for pointing me to XamarinCommunityToolkit.

**Comment by AndreiMisiukevich** [comment]
Yes, this is a bug. I will fix here and in XCT

**Comment by AndreiMisiukevich** [comment]
Or I think only in XCT
